# Generated by Django 4.0.6 on 2022-07-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
